version: 2
updates:
- package-ecosystem: pip
  directory: "/code"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: stripe
    versions:
    - 2.55.1
    - 2.55.2
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pygithub
    versions:
    - 1.54.1
  - dependency-name: jinja2
    versions:
    - 2.10.1
