language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - echo -e SECRET_KEY=\"my-test-key\" > code/.env
  - psql -c 'create database airflow_aas_test;' -U postgres
install:
  - pip install -r code/dev-requirements.txt
# command to run tests
script:
  - make

addons:
  postgresql: "9.6"

env:
  global:
    - PGDBNAME=airflow_aas_test
    - PGUSER=postgres
    - PGPASSWORD=""