version: '3'
services:
  postgres:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: airflow_aas
      POSTGRES_DB: airflow_aas_test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  reg:
