version: '3'
services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "5671:5671"
  postgres:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: airflow_aas
      POSTGRES_DB: airflow_aas
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
