version: '3'
services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "5671:5671"
  postgres:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: airflow_aas
      POSTGRES_DB: airflow_aas
    volumes:
      - pgdata:/var/lib/postgresql/data
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - reg:/var/lib/registry

volumes:
  pgdata:
  reg:
