version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5772:5672"
      - "5771:5671"
      - "15772:15672"
    environment:
      RABBITMQ_DEFAULT_VHOST: airflow_aas
  postgres:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: airflow_aas
      POSTGRES_DB: airflow_aas
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
  # psql:
  #   image: postgres:9-alpine
  #   depends_on:
  #     - postgres
  #   command:
  #     - psql
  #     - "-H postgres"
  #     - "-u airflow_aas"
  #     - "airflow_aas"
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - reg:/var/lib/registry
  vault:
    image: vault
    ports:
     - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "just-a-token"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK


volumes:
  pgdata:
  reg:
