# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 22:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cluster_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(choices=[('CLUSTER_START', 'Cluster Started'), ('CLUSTER_STOP', 'Cluster Stopped'), ('POD_START', 'Pod Started'), ('POD_STOP', 'Pod Stopped')], max_length=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cluster')),
            ],
        ),
        migrations.AddIndex(
            model_name='clusterevent',
            index=models.Index(fields=['cluster_id', '-created_at'], name='core_cluste_cluster_f65cec_idx'),
        ),
    ]
