# Generated by Django 2.0.4 on 2018-05-17 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180416_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.URLField(max_length=300)),
                ('docker_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='databaseinstance',
            name='db_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DatabaseType'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='db_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DatabaseInstance'),
        ),
    ]
