# Generated by Django 2.0.4 on 2018-05-17 20:34

from django.db import migrations, models


def up(apps, schema_editor):
    DatabaseType = apps.get_model('core', 'DatabaseType')

    for db_type in DatabaseType.objects.all():
        name, version = db_type.name.split(' ')
        db_type.varient = name
        db_type.version = version.replace('(', '').replace(')', '')
        db_type.save()


def down(apps, schema_editor):
    for db_type in DatabaseType.objects.all():
        db_type.name = f'{db_type.varient} ({db_type.version})'
        db_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180517_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasetype',
            options={'ordering': ['varient', 'version']},
        ),
        migrations.AddField(
            model_name='databasetype',
            name='varient',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databasetype',
            name='version',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.RunPython(
            up, reverse_code=down
        ),
        migrations.RemoveField(
            model_name='databasetype',
            name='name'
        ),
    ]
