# Generated by Django 2.0.4 on 2018-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180517_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='databasetype',
            name='port',
            field=models.CharField(default=5432, max_length=10),
            preserve_default=False,
        ),
    ]
