# Generated by Django 2.0.4 on 2018-05-19 20:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180519_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetype',
            name='env_map',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
