# Generated by Django 2.0.6 on 2018-06-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Repository'),
        ),
    ]
