# Generated by Django 2.0.6 on 2018-07-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cluster_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.Repository'),
        ),
    ]
