# Generated by Django 2.0.7 on 2018-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180710_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['repository_id', '-created_at'], name='repo_created_idx'),
        ),
    ]
