# Generated by Django 2.1 on 2018-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180726_1626'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='build',
            name='repo_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='clusterevent',
            name='core_cluste_cluster_f65cec_idx',
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['repository', '-created_at'], name='repo_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterevent',
            index=models.Index(fields=['cluster', '-created_at'], name='core_cluste_cluster_f65cec_idx'),
        ),
    ]
