# Generated by Django 2.1 on 2018-08-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180816_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success')], default='queued', max_length=20),
        ),
    ]
