# Generated by Django 2.1 on 2018-08-26 20:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180826_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lines', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.Build')),
            ],
        ),
    ]
