apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
spec:
  selector:
    app: worker
    role: airflow-worker
    it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
  ports:
  - port: 8793
    name: worker
  type: NodePort