apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-ui-deployment
spec:
  selector:
    matchLabels:
      app: ui
      role: airflow-ui
  template:
    metadata:
      labels:
        app: ui
        role: airflow-ui
        it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
    spec:
      containers:
      - name: ui
        image: {{ image }}
        command: ["airflow", "webserver"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      initContainers:
      - name: init-ui
        image: {{ image }}
        command: ["airflow", "initdb"]
        imagePullPolicy: Always