apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
      role: airflow-worker
  template:
    metadata:
      labels:
        app: worker
        role: airflow-worker
        it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
    spec:
      containers:
      - name: worker
        image: {{ image }}
        command: ["airflow", "worker"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8793