apiVersion: v1
kind: Service
metadata:
  name: airflow-ui
spec:
  selector:
    app: ui
    role: airflow-ui
    it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
  ports:
  - port: 8010
  type: NodePort