apiVersion: v1
kind: Service
metadata:
  name: airflow-flower
spec:
  selector:
    app: flower
    role: airflow-flower
    it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
  ports:
  - port: 6666
    name: flower
  type: NodePort