apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metadb-deployment
spec:
  selector:
    matchLabels:
      app: metadb
      role: airflow-metadb
  template:
    metadata:
      labels:
        app: metadb
        role: airflow-metadb
        it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
    spec:
      containers:
      - name: metadb
        image: "{{ image }}"
        ports:
        - containerPort: 5432
