apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metadb-deployment
spec:
  selector:
    matchLabels:
      app: metadb
      role: airflow-metadb
  template:
    metadata:
      labels:
        app: metadb
        role: airflow-metadb
        it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
    spec:
      containers:
      - name: metadb
        image: "{{ image }}"
        ports:
        - containerPort: {{ port }}
        {% if container_env %}
        env:
        {% for env_var in container_env.keys() %}
          - name: {{ env_var }}
            valueFrom:
              secretKeyRef:
                name: metadb-{{ cluster_id }}
                key: {{ env_var.lower().replace('_', '-') }}
        {% endfor %}
        {% endif %}
