apiVersion: v1
kind: Service
metadata:
  name: auth-proxy
spec:
  selector:
    app: nginx
    role: auth-proxy
    it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 80
  type: NodePort