apiVersion: v1
kind: Service
metadata:
  name: airflow-messagequeue
spec:
  selector:
    app: rabbit
    role: airflow-messagequeue
    it.justcompile.aaas.cluster_id: "{{ cluster_id }}"
  ports:
  - name: amqp
    port: 5672
  type: ClusterIP