# Generated by Django 2.0.7 on 2018-07-21 18:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(through='payments.PlanFeature', to='payments.Feature'),
        ),
    ]
