# Generated by Django 2.0.7 on 2018-07-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180721_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='payments.Feature'),
        ),
    ]
