# Generated by Django 2.1 on 2018-08-16 16:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180726_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
